#
#  Makefile.fpc for hash units example
#

[target]
programs=NullHandlerTest ConsoleHandlerTest FileHandlerTest RecordHandlerReadTest RecordHandlerTest StreamHandlerFileTest StreamHandlerStreamTest StreamHandlerStreamTStreamTest SysLogHandlerTest

[require]
packages=

[install]
fpcpackage=y

[compiler]
options=-Fu..

[default]
fpcdir=${FPCDIR}





